import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{ADDRESS,EX,connect,read,wait,write}from'./genlayer.js';import'./style.css';
const COMMIT='0b8184b1d6ed9fba836222684fd082b32782d4ef';
const short=x=>x?`${String(x).slice(0,7)}…${String(x).slice(-5)}`:'—';
const num=x=>Number(x??0);
function App(){const[wallet,setWallet]=useState(null),[config,setConfig]=useState(null),[bundleId,setBundleId]=useState('3'),[bundle,setBundle]=useState(null),[items,setItems]=useState([]),[name,setName]=useState('Core specification gate'),[category,setCategory]=useState('Core'),[eip,setEip]=useState('1559'),[commit,setCommit]=useState(COMMIT),[busy,setBusy]=useState(''),[notice,setNotice]=useState('Connect a wallet or inspect an existing bundle.');
 const role=useMemo(()=>!wallet?'OBSERVER':!bundle?'BUNDLE AUTHOR':wallet.account.toLowerCase()===String(bundle.creator).toLowerCase()?'AUTHOR':'INDEPENDENT AUDITOR',[wallet,bundle]);
 const sync=async(id=bundleId)=>{setBusy('sync');try{const b=await read('get_bundle',[Number(id)]);setBundle(b);const rows=[];for(let i=0;i<num(b.requirement_count);i++)rows.push(await read('get_requirement',[Number(id),i]));setItems(rows);setNotice('On-chain state synchronized.')}catch(e){setBundle(null);setItems([]);setNotice(e.message)}finally{setBusy('')}};
 useEffect(()=>{if(ADDRESS){read('get_config').then(setConfig).catch(e=>setNotice(e.message));sync('3')}},[]);
 const tx=async(fn,args,after=()=>sync())=>{if(!wallet)throw Error('Connect a wallet first.');setBusy(fn);try{const h=await write(wallet,fn,args);setNotice(`${fn}: submitted ${short(h)}`);await wait(h,s=>setNotice(`${fn}: ${s.label}`));await after();setNotice(`${fn}: finalized and read back from contract.`)}catch(e){setNotice(e.message)}finally{setBusy('')}};
 const create=()=>tx('create_bundle',[name,category,0],async()=>{const cfg=await read('get_config');setConfig(cfg);const id=String(cfg.bundle_count);setBundleId(id);await sync(id)});
 const add=()=>tx('add_requirement',[Number(bundleId),Number(eip),commit]);
 const state=bundle?.state||'NO BUNDLE';
 return <div className="shell"><aside><div className="identity"><img src="/spec-latch-logo.png"/><div><b>SpecLatch</b><span>EIP metadata gate</span></div></div><nav><a className="active">Release console</a><a href="#how-it-works">How it works</a><a href="https://eips.ethereum.org" target="_blank">Canonical EIPs ↗</a><a href={ADDRESS?`${EX}/address/${ADDRESS}`:'#'} target="_blank">Studionet contract ↗</a></nav><div className="scope"><b>Decision boundary</b><p>SPEC_READY verifies specification metadata only. It never proves consumer migration or deployment safety.</p></div><button className="wallet" onClick={async()=>{try{setWallet(await connect());setNotice('Wallet connected.')}catch(e){setNotice(e.message)}}}>{wallet?short(wallet.account):'Connect wallet'}</button></aside>
 <main><header><div><span className="eyebrow">PERMISSIONLESS · TWO-WALLET WORKFLOW</span><h1>Specification<br/>release gate</h1></div><div className={`signal ${state}`}><i></i><span>Current state</span><b>{state}</b></div></header>
 <section className="topline"><div><span>Network</span><b>Studionet</b></div><div><span>Connected role</span><b>{role}</b></div><div><span>Bundles</span><b>{config?.bundle_count??'—'}</b></div><div><span>Contract</span><b>{ADDRESS?short(ADDRESS):'Not deployed'}</b></div></section>
 <section className="console"><div className="rail"><div className="section-title"><span>01</span><div><b>Bundle rail</b><small>Author and seal a manifest</small></div></div><label>Bundle ID<div className="inline"><input value={bundleId} onChange={e=>setBundleId(e.target.value)}/><button className="mini" disabled={busy} onClick={()=>sync()}>Load</button></div></label><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Policy category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Core</option><option>Networking</option><option>Interface</option><option>ERC</option></select></label><button disabled={busy||!wallet||!!bundle} onClick={create}>Create new bundle</button><div className="divider"></div><label>EIP ID<input value={eip} onChange={e=>setEip(e.target.value)}/></label><label>Pinned canonical commit<input className="mono" value={commit} onChange={e=>setCommit(e.target.value.toLowerCase())}/></label><button disabled={busy||role!=='AUTHOR'||bundle?.state!=='DRAFT'} onClick={add}>Append requirement</button><button className="seal" disabled={busy||role!=='AUTHOR'||bundle?.state!=='DRAFT'||!items.length} onClick={()=>tx('seal_bundle',[Number(bundleId)])}>Seal immutable manifest</button></div>
 <div className="matrix"><div className="section-title"><span>02</span><div><b>Requirement matrix</b><small>One canonical receipt per row</small></div><em>{items.length} / 8 slots</em></div><div className="table"><div className="tr headrow"><span>EIP</span><span>Canonical facts</span><span>Dependencies</span><span>Receipt</span><span></span></div>{items.length?items.map((x,i)=><div className="tr" key={i}><span className="eipid">EIP-{String(x.eip_id)}</span><span><b>{x.title||'Awaiting source check'}</b><small>{x.status||'—'} · {x.category||bundle?.expected_category}</small></span><span className="mono">{x.requires_csv||'none'}</span><span><mark className={x.state}>{x.state}</mark><small>rev {String(x.revision)}</small></span><span><button className="check" disabled={busy||role!=='INDEPENDENT AUDITOR'||!['PENDING','SOURCE_UNAVAILABLE'].includes(x.state)||!['SEALED','VERIFYING','UNRESOLVED'].includes(bundle?.state)} onClick={()=>tx('verify_requirement',[Number(bundleId),i])}>Check source</button></span></div>):<div className="empty">No requirements loaded. Create a bundle or load an existing ID.</div>}</div></div>
 <div className="gate"><div className="section-title"><span>03</span><div><b>Deterministic gate</b><small>AI extracts facts; contract decides</small></div></div><div className="path">{['DRAFT','SEALED','VERIFYING','SPEC_READY'].map((s,i)=><React.Fragment key={s}><div className={state===s?'now':(['SEALED','VERIFYING','SPEC_READY','BLOCKED','UNRESOLVED'].indexOf(state)>i?'done':'')}><i></i><span>{s}</span></div>{i<3&&<b>→</b>}</React.Fragment>)}</div><div className="verdict"><span>Gate result</span><strong>{state}</strong><p>{bundle?.blocker_code||'The contract has not produced a terminal decision.'}</p></div><dl><dt>Manifest</dt><dd>{bundle?.manifest_digest||'Not sealed'}</dd><dt>Creator</dt><dd>{bundle?.creator||'—'}</dd><dt>Checked</dt><dd>{bundle?`${String(bundle.checked_count)} / ${String(bundle.requirement_count)}`:'—'}</dd><dt>Finalizer</dt><dd>{bundle?.finalizer||'—'}</dd></dl><button disabled={busy||role!=='INDEPENDENT AUDITOR'||!['VERIFYING','UNRESOLVED'].includes(bundle?.state)} onClick={()=>tx('finalize_bundle',[Number(bundleId)])}>Evaluate dependency gate</button></div></section>
 <section className="how" id="how-it-works"><div className="section-title"><span>04</span><div><b>How it works</b><small>A permissionless two-wallet verification flow</small></div></div><div className="steps"><article><i>1</i><b>Connect and create</b><p>Connect Wallet A, enter a bundle name and policy category, then select <strong>Create new bundle</strong>.</p></article><article><i>2</i><b>Add canonical requirements</b><p>Enter each EIP number and a full 40-character commit from ethereum/EIPs. Append every required EIP before sealing.</p></article><article><i>3</i><b>Seal the manifest</b><p>Select <strong>Seal immutable manifest</strong>. Sealing fixes the EIP list and digest; corrections require a new bundle.</p></article><article><i>4</i><b>Verify independently</b><p>Switch to a different wallet, load the bundle ID, and select <strong>Check source</strong> for every row.</p></article><article><i>5</i><b>Evaluate the gate</b><p>After all receipts are checked, select <strong>Evaluate dependency gate</strong> and wait for finality plus readback.</p></article><article><i>6</i><b>Read the result</b><p><strong>SPEC_READY</strong> means canonical EIP metadata satisfies this bundle policy. BLOCKED, CONFLICT, or UNRESOLVED must not be treated as approval.</p></article></div><div className="review-tip"><b>Reviewer shortcut</b><span>Load bundle <strong>3</strong> to inspect the verified happy path, or bundle <strong>4</strong> to inspect a fail-closed result—no wallet connection required.</span></div></section>
 <section className="sources"><div><span>PRIMARY ROUTE</span><b>eips.ethereum.org</b><p>Live canonical EIP representation, exact-bound to the selected EIP number.</p></div><div><span>PINNED FALLBACK</span><b>ethereum/EIPs @ commit</b><p>Immutable raw file at a full 40-character commit SHA, never a mutable branch.</p></div><div><span>FAIL-CLOSED</span><b>No report uploads</b><p>User-authored Markdown cannot produce SPEC_READY. Conflict and outage remain explicit states.</p></div></section></main><footer><span>{notice}</span><b>{busy?'TRANSACTION IN PROGRESS':'FINALITY + READBACK ENFORCED'}</b></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
